# Generated by Django 4.0.4 on 2022-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.CharField(max_length=250, unique=True)),
                ('Business_desc', models.CharField(max_length=500)),
                ('campaign_start', models.DateField()),
                ('campaign_end', models.DateField()),
                ('images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
